
 /*
  * This file generated by `build.js` script
  */
 
package bootstrap
 
import (
  "github.com/robertkrimen/otto/ast"
  "github.com/robertkrimen/otto/parser"
)
 
// HandlerBootstrapProgram :
var HandlerBootstrapProgram *ast.Program
 
func init() {
  HandlerBootstrapProgram, _ = parser.ParseFile(nil, "", handlerBootstrapJS, 0)
}
 
var handlerBootstrapJS string = `
  response.send = (function () {
  function send(value) {
    var v = JSON.stringify(value);
    response.write(v);
  }
  return send;
})();

var __reponse__status = response.status;

response.status = function () {
  function status(status) {
    __reponse__status(status);
    return response;
  }
  return status;
};

response.writeln = function (msg) {
  response.write(msg + "\n");
};

`
  
